config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    resources :comments
  end

   root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments

	validates :title, presence: true
	validates :description, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: 'welcome', password: 'secret',
  except: [:index, :show]
  before_action :find_article, except: [:new, :create, :index]

  def index
  	@articles = Article.all
  end

  def new
  	@article = Article.new
  end

  def create
  	@article = Article.create(allowed_params)

  	if @article.valid?
  		redirect_to articles_path
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	@article.update_attributes(allowed_params)

  	redirect_to articles_path
  end

  def show
  end

  def destroy
  	@article.destroy

  	redirect_to articles_path, notice: 'Delete success'
  end

  def allowed_params
  	params.require(:article).permit(:title, :description)
  end

  def find_article
  	@article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article = Article.find(params[:article_id])
		allowed_params = params[:comment].permit(:commenter, :description)
		@comment = @article.comments.create(allowed_params)

		redirect_to @article
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy

		redirect_to @article
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

	<% if @article.errors.any? %>
		<div id="error_explanation">
		<h2>
			<%= pluralize(@article.errors.count, 'error') %> prohibited this article from being saved.
		</h2>
		<ul>
        		<% @article.errors.full_messages.each do |m| %>
          		<li><%= m %></li>
        		<% end %>
      	</ul>
      	</div>
	<% end %>

	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>

<% @articles.each do |article| %>

<%= article.title %>
<%= article.description %>

<%= link_to 'Edit', edit_article_path(article) %>
<%= link_to 'Show', article %>
<%= link_to 'Delete', article_path(article), method: :delete,
			data: { confirm: 'Are you sure?' } %>

<br>

<% end %>
<br>
<%= link_to 'New article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<p>
	<%= @article.title %>
</p>

<p>
	<%= @article.description %>
</p>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>
<p>
	<strong>Commenter:</strong>
	<%= comment.commenter %>
</p>
<p>
	<strong>Comment:</strong>
	<%= comment.description %>
</p>

<p>
  <%= link_to 'Destroy Comment', article_comment_path(@article, comment),
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %><br>
		<%= f.text_field :commenter %>
	</p>

	<p>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, message| %>
	<%= content_tag :div, message, class:name %>
<% end %>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello Rails</h1>
<%= link_to 'My Blog', articles_url %>